export const BEER_API_ENDPOINT = process.env.NEXT_PUBLIC_BEER_API_ENDPOINT;
export const BEER_API_PAGE_SIZE = process.env.NEXT_PUBLIC_BEER_API_PAGE_SIZE;
export const BEER_API_DOCUMENTATION = process.env.NEXT_PUBLIC_BEER_API_DOCUMENTATION;